echo  '*Test Date:*'
echo  '*Environment:*'
echo  '*Scenario:*'
echo  '*Description:*'
echo  '*Reproduce steps:*'
echo  '*Expected result:*'
echo  '*Actual result:*'
echo  '*Affected Cases*'
echo  '{code}'
echo  '{code}'
echo  'The test is completed, the scenario can be used for Staging.'